<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeminjamanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('Peminjaman')->insert([
            [
                'id_fasilitas' => 1,
                'id_peminjam' => 1,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-20',
                'tanggal_peminjaman' => '2026-04-27',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '12:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 500.000',
                'keterangan' => 'Acara berjalan lancar',
                'keperluan' => 'Workshop Web Development',
            ],
            [
                'id_fasilitas' => 2,
                'id_peminjam' => 2,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-21',
                'tanggal_peminjaman' => '2026-04-28',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '16:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => 'Pembayaran Rp 300.000',
                'keterangan' => '',
                'keperluan' => 'Meeting ORMAWA',
            ],
            [
                'id_fasilitas' => 3,
                'id_peminjam' => 3,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-22',
                'tanggal_peminjaman' => '2026-04-29',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '11:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => 'Pembayaran Rp 250.000',
                'keterangan' => '',
                'keperluan' => 'Praktikum Semester',
            ],
            [
                'id_fasilitas' => 1,
                'id_peminjam' => 4,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-19',
                'tanggal_peminjaman' => '2026-04-26',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '17:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 500.000',
                'keterangan' => 'Jumlah peserta: 35 orang',
                'keperluan' => 'Seminar Teknik Informatika',
            ],
            [
                'id_fasilitas' => 4,
                'id_peminjam' => 5,
                'id_admin' => 3,
                'tanggal_pengajuan' => '2026-04-23',
                'tanggal_peminjaman' => '2026-04-30',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '14:00:00',
                'status_peminjaman' => 'Pending',
                'administrasi_peminjaman' => '',
                'keterangan' => '',
                'keperluan' => 'Diskusi Literasi Digital',
            ],
            [
                'id_fasilitas' => 5,
                'id_peminjam' => 1,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-24',
                'tanggal_peminjaman' => '2026-05-01',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '18:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => '',
                'keterangan' => '',
                'keperluan' => 'Turnamen Olahraga Antar Prodi',
            ],
            [
                'id_fasilitas' => 6,
                'id_peminjam' => 2,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-25',
                'tanggal_peminjaman' => '2026-05-02',
                'jam_mulai' => '11:00:00',
                'jam_selesai' => '13:00:00',
                'status_peminjaman' => 'Pending',
                'administrasi_peminjaman' => '',
                'keterangan' => '',
                'keperluan' => 'Meeting dengan Dekan',
            ],
            [
                'id_fasilitas' => 3,
                'id_peminjam' => 3,
                'id_admin' => 3,
                'tanggal_pengajuan' => '2026-04-18',
                'tanggal_peminjaman' => '2026-04-25',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 250.000',
                'keterangan' => 'Lancar tanpa kendala',
                'keperluan' => 'Penelitian Data Mining',
            ],
            [
                'id_fasilitas' => 7,
                'id_peminjam' => 4,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-26',
                'tanggal_peminjaman' => '2026-05-03',
                'jam_mulai' => '15:00:00',
                'jam_selesai' => '17:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => 'Pembayaran Rp 400.000',
                'keterangan' => '',
                'keperluan' => 'Rekaman Podcast Mahasiswa',
            ],
            [
                'id_fasilitas' => 2,
                'id_peminjam' => 5,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-27',
                'tanggal_peminjaman' => '2026-05-04',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:30:00',
                'status_peminjaman' => 'Pending',
                'administrasi_peminjaman' => '',
                'keterangan' => '',
                'keperluan' => 'Rapat Koordinasi Departemen',
            ],
            [
                'id_fasilitas' => 4,
                'id_peminjam' => 2,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-15',
                'tanggal_peminjaman' => '2026-04-22',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '12:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 200.000',
                'keterangan' => 'Peserta 60 orang',
                'keperluan' => 'Diskusi Literasi Digital',
            ],
            [
                'id_fasilitas' => 5,
                'id_peminjam' => 3,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-12',
                'tanggal_peminjaman' => '2026-04-20',
                'jam_mulai' => '15:00:00',
                'jam_selesai' => '17:30:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 350.000',
                'keterangan' => 'Cuaca cerah, lapangan siap',
                'keperluan' => 'Latihan UKM Olahraga',
            ],
            [
                'id_fasilitas' => 6,
                'id_peminjam' => 1,
                'id_admin' => 3,
                'tanggal_pengajuan' => '2026-04-14',
                'tanggal_peminjaman' => '2026-04-23',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 150.000',
                'keterangan' => 'Meeting berjalan efektif',
                'keperluan' => 'Rapat Himpunan Mahasiswa',
            ],
            [
                'id_fasilitas' => 7,
                'id_peminjam' => 5,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-16',
                'tanggal_peminjaman' => '2026-04-24',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '16:00:00',
                'status_peminjaman' => 'Selesai',
                'administrasi_peminjaman' => 'Pembayaran Rp 250.000',
                'keterangan' => 'Peralatan lengkap',
                'keperluan' => 'Rekaman Podcast',
            ],
            [
                'id_fasilitas' => 2,
                'id_peminjam' => 3,
                'id_admin' => 2,
                'tanggal_pengajuan' => '2026-04-29',
                'tanggal_peminjaman' => '2026-05-06',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => 'Pembayaran Rp 300.000',
                'keterangan' => '',
                'keperluan' => 'Pelatihan Organisasi',
            ],
            [
                'id_fasilitas' => 1,
                'id_peminjam' => 2,
                'id_admin' => 1,
                'tanggal_pengajuan' => '2026-04-28',
                'tanggal_peminjaman' => '2026-05-07',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '11:00:00',
                'status_peminjaman' => 'Disetujui',
                'administrasi_peminjaman' => 'Pembayaran Rp 500.000',
                'keterangan' => '',
                'keperluan' => 'Pelatihan Publik Speaking',
            ],
        ]);
    }
}
